<?php
	$dictionary['COMP_Competition']['fields']['equipment'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Equipment',
		'required' => false,
		'name' => 'equipment',
		'vname' => 'LBL_EQUIPMENT',
		'type' => 'multienum',
		'massupdate' => '0',
		'default' => '^^',
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'size' => '20',
		'options' => 'equipment_list',
		'studio' => 'visible',
		'isMultiSelect' => true,
		'id' => 'COMP_Competitionequipment',
	);
?>