<?php
	$dictionary['COMP_Competition']['fields']['manufacturing_type'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Mfg Type',
		'required' => false,
		'name' => 'manufacturing_type',
		'vname' => 'LBL_MANUFACTURING_TYPE',
		'type' => 'enum',
		'massupdate' => '0',
		'default' => NULL,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => 100,
		'size' => '20',
		'options' => 'manufacturing_type_list',
		'studio' => 'visible',
		'dependency' => false,
		'id' => 'COMP_Competitionmanufacturing_type',
	);
?>