<?php
	$dictionary['AOS_Product_Categories']['fields']['material_cost_type_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Material Cost Type',
		'required' => false,
		'name' => 'material_cost_type_c',
		'vname' => 'LBL_MATERIAL_COST_TYPE',
		'type' => 'varchar',
		'massupdate' => '0',
		'default' => '',
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '255',
		'size' => '20',
		'id' => 'AOS_Product_Categoriesmaterial_cost_type_c',
	);
?>