<?php
	$dictionary['AOS_Product_Categories']['fields']['material_cost_type_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Material Cost Type',
		'required' => true,
		'source' => 'custom_fields',
		'name' => 'material_cost_type_c',
		'vname' => 'LBL_MATERIAL_COST_TYPE',
		'type' => 'enum',
		'massupdate' => '0',
		'default' => NULL,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => 100,
		'size' => '20',
		'options' => 'pc_material_cost_type_list',
		'studio' => 'visible',
		'dependency' => false,
		'id' => 'AOS_Product_Categoriesmaterial_cost_type_c',
	);
?>