<?php
	$dictionary['AOS_Product_Categories']['fields']['company_no_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'ERP ID',
		'required' => false,
		'name' => 'company_no_c',
		'vname' => 'LBL_COMPANY_NO',
		'type' => 'enum',
		'massupdate' => '0',
		'default' => NULL,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => 100,
		'size' => '20',
		'options' => 'erp_id_dom',
		'studio' => 'visible',
		'dependency' => false,
		'id' => 'AOS_Product_Categoriescompany_no_c',
	);
?>