<?php
  $dictionary['Lead']['fields']['specific_area_of_interest_c'] = array(
    'inline_edit' => '1',
    'labelValue' => 'Specific Area of Interest',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'specific_area_of_interest_c',
    'vname' => 'LBL_SPECIFIC_AREA_OF_INTEREST',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'specific_area_of_interest_list',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'Leadsspecific_area_of_interest_c',
  );
?>