<?php
	$dictionary['ODR_SalesOrders']['fields']['ship_via_c'] = array (
		'inline_edit' => '1',
    'labelValue' => 'Ship Via',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'ship_via_c',
    'vname' => 'LBL_SHIP_VIA',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id' => 'ODR_SalesOrdersship_via_c',
	);
?>