<?php
	$dictionary['ODR_SalesOrders']['fields']['po_number_c'] = array (
    'inline_edit' => '1',
    'labelValue' => 'PO Number',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'po_number_c',
    'vname' => 'LBL_PO_NUMBER',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id' => 'ODR_SalesOrderspo_number_c',
	);
?>