<?php
	$dictionary['ODR_SalesOrders']['fields']['misc_amount_c'] = array (
		'inline_edit' => '1',
    'labelValue' => 'Misc',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'misc_amount_c',
    'vname' => 'LBL_MISC_AMOUNT',
    'type' => 'currency',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '26',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'id' => 'ODR_SalesOrdersmisc_amount_c',
	);
?>