<?php
	$dictionary['ODR_SalesOrders']['fields']['order_type_c'] = array (
		'inline_edit' => '1',
    'labelValue' => 'Order Type',
    'required' => false,
    //'source' => 'custom_fields',
    'name' => 'order_type_c',
    'vname' => 'LBL_ORDER_TYPE',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'order_type_list',
    'studio' => 'visible',
    'dependency' => false,
    //'id' => 'ODR_SalesOrdersorder_type_c',
	);
?>