<?php
	$dictionary['ODR_SalesOrders']['fields']['order_date_c'] = array (
		'inline_edit' => '1',
    'labelValue' => 'Order Date',
    'required' => false,
    //'source' => 'custom_fields',
    'name' => 'order_date_c',
    'vname' => 'LBL_ORDER_DATE',
    'type' => 'date',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => true,
    'options' => 'date_range_search_dom',
	);
?>