<?php
 // created: 2020-08-21 17:30:38
$dictionary['DSBTN_DistributionItems']['fields']['status_c'] = array(
    'inline_edit' => '1',
    'labelValue' => 'Status',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'status_c',
    'vname' => 'LBL_STATUS',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'distribution_item_status_list',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'DSBTN_DistributionItemsstatus_c',
);
 ?>