<?php

$dictionary['asol_Process'] = array(
	'table'=>'asol_process',
	'audited'=>true,
	'fields'=>array (
		  'status' => 
		  array (
		    'required' => false,
		    'name' => 'status',
		    'vname' => 'LBL_STATUS',
		    'type' => 'enum',
		    'massupdate' => 0,
		    'default' => 'inactive',
		    'comments' => '',
		    'help' => '',
		    'importable' => 'true',
		    'duplicate_merge' => 'disabled',
		    'duplicate_merge_dom_value' => '0',
		    'audited' => false,
		    'reportable' => true,
		    'len' => 100,
		    'size' => '20',
		    'options' => 'wfm_process_status_list',
		    'studio' => 'visible',
		    'dependency' => false,
		  //'popupHelp' => 'click help',
		  //'help' => 'hover help',
		  ),
			'async' =>
			array (
					'required' => false,
					'name' => 'async',
					'vname' => 'LBL_ASYNC',
					'type' => 'enum',
					'massupdate' => 0,
					'default' => 'sync',
					'comments' => '',
					'help' => '',
					'importable' => 'true',
					'duplicate_merge' => 'disabled',
					'duplicate_merge_dom_value' => '0',
					'audited' => false,
					'reportable' => true,
					'len' => 100,
					'size' => '20',
					'options' => 'wfm_process_async_list',
					'studio' => 'visible',
					'dependency' => false,
					//'popupHelp' => 'click help',
					//'help' => 'hover help',
			),
		  'trigger_module' => 
		  array (
		    'required' => false,
		    'name' => 'trigger_module',
		    'vname' => 'LBL_TRIGGER_MODULE',
		    'type' => 'enum',
		    'massupdate' => 0,
		    'comments' => '',
		    'help' => '',
		    'importable' => 'true',
		    'duplicate_merge' => 'disabled',
		    'duplicate_merge_dom_value' => '0',
		    'audited' => false,
		    'reportable' => true,
		    'len' => 100,
		    'size' => '20',
		    'options' => 'moduleList',
		    'studio' => 'visible',
		    'dependency' => false,
		  ),
		  
		  'alternative_database' =>
		  array (
		    'name' => 'alternative_database',
		    'vname' => 'LBL_REPORT_USE_ALTERNATIVE_DB',
		    'type' => 'varchar',
		    'len' => '255',
		    'default' => '-1', 
		    'comment' => 'Non CRM Database usage definition',
		  ),
			
			'audit' =>
			array(
				'name' => 'audit',
				'vname' => 'LBL_AUDIT',
				'type' => 'bool',
				'default' => 0,
				'reportable' => false,
			),
			
			'data_source' =>
			array (
				'required' => false,
				'name' => 'data_source',
				'vname' => 'LBL_DATA_SOURCE',
				'type' => 'enum',
				'massupdate' => 0,
				'default' => 'database',
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => false,
				'reportable' => true,
				'len' => 100,
				'size' => '20',
				'options' => 'wfm_process_data_source_list',
				'studio' => 'visible',
				'dependency' => false,
				//'popupHelp' => 'click help',
				//'help' => 'hover help',
			),
			
			'asol_forms_id_c' =>
			array (
				'required' => false,
				'name' => 'asol_forms_id_c',
				'vname' => 'LBL_FORM_ASOL_FORMS_ID',
				'type' => 'id',
				'massupdate' => 0,
				'no_default' => false,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => 0,
				'audited' => false,
				'reportable' => false,
				'unified_search' => false,
				'merge_filter' => 'disabled',
				'len' => 36,
				'size' => '20',
			),
			'form' =>
			array (
				'required' => false,
				'source' => 'non-db',
				'name' => 'form',
				'vname' => 'LBL_FORM',
				'type' => 'relate',
				'massupdate' => 0,
				'no_default' => false,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => false,
				'reportable' => true,
				'unified_search' => false,
				'merge_filter' => 'disabled',
				'len' => '255',
				'size' => '20',
				'id_name' => 'asol_forms_id_c',
				'ext2' => 'asol_Forms',
				'module' => 'asol_Forms',
				'rname' => 'name',
				'quicksearch' => 'enabled',
				'studio' => 'visible',
			),
		  
		  'event_counter' => 
		  array (
		    'required' => false,
		    'name' => 'event_counter',
		    'vname' => 'LBL_EVENT_COUNTER',
		    'type' => 'int',
		    'massupdate' => 0,
		    'comments' => '',
		    'help' => '',
		    'importable' => 'true',
		    'duplicate_merge' => 'disabled',
		    'duplicate_merge_dom_value' => '0',
		    'audited' => false,
		    'reportable' => true,
		    //'len' => '2',
		    'size' => '20',
		  	'default' => '0',
		  ),
		  'activity_counter' => 
		  array (
		    'required' => false,
		    'name' => 'activity_counter',
		    'vname' => 'LBL_ACTIVITY_COUNTER',
		    'type' => 'int',
		    'massupdate' => 0,
		    'comments' => '',
		    'help' => '',
		    'importable' => 'true',
		    'duplicate_merge' => 'disabled',
		    'duplicate_merge_dom_value' => '0',
		    'audited' => false,
		    'reportable' => true,
		    //'len' => '2',
		    'size' => '20',
		  	'default' => '0',
		  ),
		  'task_counter' => 
		  array (
		    'required' => false,
		    'name' => 'task_counter',
		    'vname' => 'LBL_TASK_COUNTER',
		    'type' => 'int',
		    'massupdate' => 0,
		    'comments' => '',
		    'help' => '',
		    'importable' => 'true',
		    'duplicate_merge' => 'disabled',
		    'duplicate_merge_dom_value' => '0',
		    'audited' => false,
		    'reportable' => true,
		    //'len' => '2',
		    'size' => '20',
		  	'default' => '0',
		  ),
		  'wfe_operation_counter' => 
		  array (
		    'required' => false,
		    'name' => 'wfe_operation_counter',
		    'vname' => 'LBL_WFE_OPERATION_COUNTER',
		    'type' => 'int',
		    'massupdate' => 0,
		    'comments' => '',
		    'help' => '',
		    'importable' => 'true',
		    'duplicate_merge' => 'disabled',
		    'duplicate_merge_dom_value' => '0',
		    'audited' => false,
		    'reportable' => true,
		    //'len' => '2',
		    'size' => '20',
		  	'default' => '0',
		  ),
		
	),
	'relationships'=>array (
	),
	'optimistic_locking'=>true,
);
if (!class_exists('VardefManager')){
	require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('asol_Process','asol_Process', array('basic','assignable'));