<?php
	$dictionary['MGMT_ManagementReports']['fields']['module_url_c'] = array (
		'inline_edit' => '',
		'labelValue' => 'Module URL',
		'required' => true,
		'name' => 'module_url_c',
		'vname' => 'LBL_MODULE_URL',
		'type' => 'varchar',
		'massupdate' => '0',
		'default' => '',
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '255',
		'size' => '20',
		'id' => 'MGMT_ManagementReportsmodule_url_c',
	);
?>