<?php
 // created: 2020-09-02 08:52:39
// $dictionary['CI_CustomerItems']['fields']['market_c'] = array (
//     'inline_edit' => '1',
//     'labelValue' => 'Market OLD',
//     'required' => false,
//     'source' => 'non-db',
//     'name' => 'market_c',
//     'vname' => 'LBL_MARKET',
//     'type' => 'relate',
//     'massupdate' => '0',
//     'default' => NULL,
//     'no_default' => false,
//     'comments' => '',
//     'help' => '',
//     'importable' => 'true',
//     'duplicate_merge' => 'disabled',
//     'duplicate_merge_dom_value' => '0',
//     'audited' => false,
//     'reportable' => true,
//     'unified_search' => false,
//     'merge_filter' => 'disabled',
//     'len' => '255',
//     'size' => '20',
//     'id_name' => 'mkt_markets_id_c',
//     'ext2' => 'MKT_Markets',
//     'module' => 'MKT_Markets',
//     'rname' => 'name',
//     'quicksearch' => 'enabled',
//     'studio' => 'visible',
//     'id' => 'CI_CustomerItemsmarket_c',
// );
 ?>