<?php

$dictionary['asol_WorkingNodes'] = array(
	'table'=>'asol_workingnodes',
	'audited'=>true,
	'fields'=>array (
  
  'type' => 
  array (
    'required' => false,
    'name' => 'type',
    'vname' => 'LBL_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'start',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'wfm_events_type_list',
    'studio' => 'visible',
    'dependency' => false,
  ),

  'asol_processinstances_id_c' => 
  array (
    'required' => false,
    'name' => 'asol_processinstances_id_c',
    'vname' => '',
    'type' => 'id',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => true,
    'len' => 36,
    'size' => '20',
  ),
  'process_instance_id' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'process_instance_id',
    'vname' => 'LBL_PROCESS_INSTANCE_ID',
    'type' => 'relate',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'id_name' => 'asol_processinstances_id_c',
    'ext2' => 'asol_ProcessInstances',
    'module' => 'asol_ProcessInstances',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'priority' => 
  array (
    'required' => false,
    'name' => 'priority',
    'vname' => 'LBL_PRIORITY',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '6',
    'size' => '20',
    'disable_num_format' => '',
  ),
  //////////////
  'asol_events_id_c' => 
  array (
    'required' => false,
    'name' => 'asol_events_id_c',
    'vname' => '',
    'type' => 'id',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => true,
    'len' => 36,
    'size' => '20',
  ),
  'event' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'event',
    'vname' => 'LBL_EVENT',
    'type' => 'relate',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'id_name' => 'asol_events_id_c',
    'ext2' => 'asol_Events',
    'module' => 'asol_Events',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  //////////////
  'asol_activity_id_c' => 
  array (
    'required' => false,
    'name' => 'asol_activity_id_c',
    'vname' => '',
    'type' => 'id',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => true,
    'len' => 36,
    'size' => '20',
  ),
  'current_activity' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'current_activity',
    'vname' => 'LBL_CURRENT_ACTIVITY',
    'type' => 'relate',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'id_name' => 'asol_activity_id_c',
    'ext2' => 'asol_Activity',
    'module' => 'asol_Activity',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  ///////////
  'object_ids' => 
  array (
    'name' => 'object_ids',
    'type' => 'longtext',
    'isnull' => true,
  ),
  'iter_object' => 
  array (
    'required' => false,
    'name' => 'iter_object',
    'vname' => 'LBL_ITER_OBJECT',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '11',
    'size' => '20',
    'disable_num_format' => '',
  ),
  
  ///+++
  ///////////
  'parent_name'=>
  array(
    'name'=> 'parent_name',
    'parent_type'=>'record_type_display' ,
    'type_name'=>'parent_type',
    'id_name'=>'parent_id',
    'vname'=>'LBL_EXECUTING_OBJECT',
    'type'=>'parent',
    'group'=>'parent_name',
    'source'=>'non-db',
    'options'=> 'moduleList',
  ),
  'parent_type' =>// trigger_module
  array (
    'required' => false,
    'name' => 'parent_type',
    'vname' => 'LBL_TRIGGER_MODULE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'Home',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'group'=>'bean',
    'options' => 'moduleList',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'parent_id' =>// bean_id
  array (
    'required' => false,
    'name' => 'parent_id',
    'vname' => 'LBL_BEAN_ID',
    'type' => 'id',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'group'=>'bean',
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  ////////////
  ///+++
  
  ///////////
  'asol_task_id_c' => 
  array (
    'required' => false,
    'name' => 'asol_task_id_c',
    'vname' => '',
    'type' => 'id',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => true,
    'len' => 36,
    'size' => '20',
  ),
  'current_task' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'current_task',
    'vname' => 'LBL_CURRENT_TASK',
    'type' => 'relate',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'id_name' => 'asol_task_id_c',
    'ext2' => 'asol_Task',
    'module' => 'asol_Task',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'delay_wakeup_time' => 
  array (
    'required' => false,
    'name' => 'delay_wakeup_time',
    'vname' => 'LBL_DELAY_WAKEUP_TIME',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'dbType' => 'datetime',
  ),
  /*
  'status' => 
  array (
    'required' => false,
    'name' => 'status',
    'vname' => 'LBL_STATUS',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '20',
    'size' => '20',
  ),
  */
  //////////////
  'status' => 
  array (
    'required' => false,
    'name' => 'status',
    'vname' => 'LBL_STATUS',
    'type' => 'enum',
    'massupdate' => 0,
    //'default' => 'start',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'wfm_working_node_status',
    'studio' => 'visible',
    'dependency' => false,
  ),
  //////////////  
  'old_bean' => 
  array (
    'name' => 'old_bean',
    'type' => 'longtext',
    'isnull' => true,
  ),
  'new_bean' => 
  array (
    'name' => 'new_bean',
    'type' => 'longtext',
    'isnull' => true,
  ),
  'custom_variables' => 
  array (
    'name' => 'custom_variables',
    'type' => 'longtext',
    'isnull' => true,
  ),
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('asol_WorkingNodes','asol_WorkingNodes', array('basic','assignable'));