<?php
  $dictionary['Opportunity']['fields']['amount_weighted_c'] = array(
    'inline_edit' => '1',
      'labelValue' => 'amount weighted',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'amount_weighted_c',
      'vname' => 'LBL_AMOUNT_WEIGHTED',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 2,
      'id' => 'Opportunitiesamount_weighted_c',
  );
?>