<?php
  $dictionary['Opportunity']['fields']['annual_volume_lbs_c'] = array(
    'inline_edit' => '1',
    'labelValue' => 'Annual Volume/Lbs',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'annual_volume_lbs_c',
    'vname' => 'LBL_ANNUAL_VOLUME_LBS',
    'type' => 'int',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => 999000000,
    'validation' => 
    array (
      'type' => 'range',
      'min' => false,
      'max' => 999000000,
    ),
    'id' => 'Opportunitiesannual_volume_lbs_c',
  );
?>