<?php
 // created: 2023-06-12 13:24:07
 $dictionary['OTR_OnTrack']['fields']['steps_to_replicate_the_issue_c'] = array (
    'inline_edit' => '1',
    'labelValue' => 'Steps to Replicate the Issue',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'steps_to_replicate_the_issue_c',
    'vname' => 'LBL_STEPS_TO_REPLICATE_THE_ISSUE',
    'type' => 'text',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
    'id' => 'OTR_OnTracksteps_to_replicate_the_issue_c',
    'editor' => 'html',
 );
?>