<?php
	$dictionary['User']['fields']['sales_group_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Sales Group',
		'required' => false,
		'source' => 'custom_fields',
		'name' => 'sales_group_c',
		'vname' => 'LBL_SALES_GROUP',
		'type' => 'enum',
		'massupdate' => '0',
		'default' => NULL,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => 100,
		'size' => '20',
		'function' => 'getSalesGroupForReports',
		'options' => '',
		'studio' => 'visible',
		'dependency' => NULL,
		'id' => 'Userssales_group_c',
	);
?>