<?php
	$dictionary['User']['fields']['department'] = array (
    'inline_edit' => '1',
    'labelValue' => 'Department',
    'required' => true,
    'name' => 'department',
    'vname' => 'LBL_DEPARTMENT',
    'type' => 'enum',
    'massupdate' => '1',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'user_department_list',
    'studio' => 'visible',
    'dependency' => NULL,
    'id' => 'Usersdepartment',
	);
?>