<?php
 // created: 2021-04-21 14:51:22
 $dictionary['TRI_TechnicalRequestItems']['fields']['division_c'] = array (
    'inline_edit' => '1',
    'labelValue' => 'Division',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'division_c',
    'vname' => 'LBL_DIVISION',
    'type' => 'enum',
    'massupdate' => '1',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'user_division_list',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'TRI_TechnicalRequestItemsdivision_c',
 );
?>