<?php
 // created: 2022-06-13 07:16:15
 $dictionary['TR_TechnicalRequests']['fields']['raw_material_substitutions_c'] = array (
    'inline_edit' => '1',
    'labelValue' => 'Raw Material Substitutions',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'raw_material_substitutions_c',
    'vname' => 'LBL_RAW_MATERIAL_SUBSTITUTIONS',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'raw_material_substitutions_list',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'TR_TechnicalRequestsraw_material_substitutions_c',
 );
?>