<?php
  // created: 2020-06-15 02:26:33
  $dictionary['TR_TechnicalRequests']['fields']['mmp_medical_c'] = array (
    'inline_edit' => '1',
    'labelValue' => 'MMP/Medical',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'mmp_medical_c',
    'vname' => 'LBL_MMP_MEDICAL',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'ups_class_list',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'TR_TechnicalRequestsmmp_medical_c',
  );
?>