<?php
 // created: 2022-08-16 06:26:58
//  $dictionary['TR_TechnicalRequests']['fields']['resin_shipped_c'] = array (
//     'inline_edit' => '1',
//     'labelValue' => 'Shipped',
//     'required' => false,
//     'source' => 'custom_fields',
//     'name' => 'resin_shipped_c',
//     'vname' => 'LBL_RESIN_SHIPPED',
//     'type' => 'enum',
//     'massupdate' => '0',
//     'default' => '',
//     'no_default' => false,
//     'comments' => '',
//     'help' => '',
//     'importable' => 'true',
//     'duplicate_merge' => 'disabled',
//     'duplicate_merge_dom_value' => '0',
//     'audited' => true,
//     'reportable' => true,
//     'unified_search' => false,
//     'merge_filter' => 'disabled',
//     'len' => 100,
//     'size' => '20',
//     'options' => 'resin_shipped_list',
//     'studio' => 'visible',
//     'dependency' => false,
//     'id' => 'TR_TechnicalRequestsresin_shipped_c',
//  );
?>