<?php
    // created: 2021-05-04 05:26:00
    $dictionary['TR_TechnicalRequests']['fields']['special_effects_c'] = array (
        'inline_edit' => '1',
        'labelValue' => 'Special Effects',
        'required' => false,
        'source' => 'custom_fields',
        'name' => 'special_effects_c',
        'vname' => 'LBL_SPECIAL_EFFECTS',
        'type' => 'enum',
        'massupdate' => '0',
        'default' => '',
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 100,
        'size' => '20',
        'options' => 'special_effects_list',
        'studio' => 'visible',
        'dependency' => false,
        'id' => 'TR_TechnicalRequestsspecial_effects_c',
    );
?>