<?php
 // created: 2024-08-13 07:38:01
$dictionary['AOS_Products']['fields']['brand_c'] = array (
    'inline_edit' => '1',
    'labelValue' => 'Brand',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'brand_c',
    'vname' => 'LBL_BRAND',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pm_brand_list',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'AOS_Productsbrand_c',
);