<?php
	$dictionary['AOS_Products']['fields']['project_id_c'] = array (
		'inline_edit' => 1,
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'project_id_c',
    'vname' => 'LBL_PROJECT_PROJECT_ID',
    'type' => 'id',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '36',
    'size' => '20',
    'id' => 'AOS_Productsproject_id_c',
	);
?>