<?php
	$dictionary['AOS_Products']['fields']['budget_oct_c'] = array (
		'inline_edit' => '1',
    'labelValue' => 'October Budget',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'budget_oct_c',
    'vname' => 'LBL_BUDGET_OCT',
    'type' => 'currency',
    'massupdate' => '0',
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '26',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'id' => 'AOS_Productsbudget_oct_c',
	);
?>