<?php
	$dictionary['AOS_Products']['fields']['location_c'] = array (
		'inline_edit' => '1',
    'labelValue' => 'Location',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'location_c',
    'vname' => 'LBL_LOCATION',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '3',
    'size' => '20',
    'id' => 'AOS_Productslocation_c',
	);
?>