<?php
	$dictionary['AOS_Products']['fields']['container_c'] = array (
		'inline_edit' => '1',
    'labelValue' => 'Container',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'container_c',
    'vname' => 'LBL_CONTAINER',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'product_container_list',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'AOS_Productscontainer_c',
	);
?>