<?php
	$dictionary['AOS_Products']['fields']['project_c'] = array (
		'inline_edit' => '1',
    'labelValue' => 'Project',
    'required' => false,
    'source' => 'non-db',
    'name' => 'project_c',
    'vname' => 'LBL_PROJECT',
    'type' => 'relate',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'project_id_c',
    'ext2' => 'Project',
    'module' => 'Project',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
    'id' => 'AOS_Productsproject_c',
	);
?>