<?php
	$dictionary['AOS_Products']['fields']['company_no_c'] = array (
		'inline_edit' => '1',
    'labelValue' => 'ERP ID',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'company_no_c',
    'vname' => 'LBL_COMPANY_NO',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'erp_id_dom',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'AOS_Productscompany_no_c',
	);
?>