<?php
 // created: 2020-08-20 13:42:15
$dictionary['AOS_Products']['fields']['complexity_c'] = array(
    'inline_edit' => '1',
    'labelValue' => 'Complexity',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'complexity_c',
    'vname' => 'LBL_COMPLEXITY',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'complexity_list',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'AOS_Productscomplexity_c',
);
 ?>