<?php
    $dictionary["AOS_Products_Quotes"]["fields"]["cases"] = array (
        'name' => 'cases',
        'vname' => 'LBL_CASES',
        'type' => 'link',
        'relationship' => 'cases_aos_products_quotes',
        'module' => 'Cases',
        'bean_name' => 'Cases',
        'source' => 'non-db',
    );

    $dictionary['AOS_Products_Quotes']['fields']['lot_id'] = array (
        'inline_edit' => 1,
        'required' => false,
        'name' => 'lot_id',
        'vname' => 'LBL_LOT_ID',
        'type' => 'id',
        'massupdate' => '0',
        'default' => NULL,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '36',
        'size' => '20',
    );

    $dictionary['AOS_Products_Quotes']['fields']['lot_name'] = array (
        'inline_edit' => 1,
        'required' => false,
        'name' => 'lot_name',
        'vname' => 'LBL_LOT_NUMBER',
        'type' => 'varchar',
        'massupdate' => '0',
        'default' => NULL,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
    );

    $dictionary['AOS_Products_Quotes']['fields']['customer_product_id'] = array (
        'inline_edit' => 1,
        'required' => false,
        'name' => 'customer_product_id',
        'vname' => 'LBL_LOT_ID',
        'type' => 'id',
        'massupdate' => '0',
        'default' => NULL,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '36',
        'size' => '20',
    );

    $dictionary['AOS_Products_Quotes']['fields']['customer_product_number'] = array (
        'inline_edit' => 1,
        'required' => false,
        'name' => 'customer_product_number',
        'vname' => 'LBL_PRODUCT_NUMBER',
        'type' => 'varchar',
        'massupdate' => '0',
        'default' => NULL,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
    );

    $dictionary['AOS_Products_Quotes']['fields']['customer_product_name'] = array (
        'inline_edit' => 1,
        'required' => false,
        'name' => 'customer_product_name',
        'vname' => 'LBL_PRODUCT_NAME',
        'type' => 'varchar',
        'massupdate' => '0',
        'default' => NULL,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
    );

    $dictionary['AOS_Products_Quotes']['fields']['customer_product_amount_lbs'] = array (
        'inline_edit' => 1,
        'required' => false,
        'name' => 'customer_product_amount_lbs',
        'vname' => 'LBL_PRODUCT_AMOUNT_LBS',
        'type' => 'int',
        'massupdate' => '0',
        'default' => NULL,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '18',
        'size' => '20',
    );
?>