<?php
	$dictionary['Account']['fields']['account_class_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Account Class',
		'required' => false,
		'source' => 'custom_fields',
		'name' => 'account_class_c',
		'vname' => 'LBL_ACCOUNT_CLASS',
		'type' => 'enum',
		'massupdate' => '0',
		'default' => '',
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => 100,
		'size' => '20',
		'options' => 'account_class_list',
		'studio' => 'visible',
		'dependency' => false,
		'id' => 'Accountsaccount_class_c',
	);
?>