<?php
  $dictionary['Account']['fields']['sls_lytd_c'] = array(
    'inline_edit' => '',
    'labelValue' => 'Sales LYTD',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'sls_lytd_c',
    'vname' => 'LBL_SLS_LYTD',
    'type' => 'decimal',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '0',
    'id' => 'Accountssls_lytd_c',
  );
?>