<?php
  $dictionary['Account']['fields']['integration_date_c'] = array(
    'inline_edit' => '1',
    'labelValue' => 'Integration Date',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'integration_date_c',
    'vname' => 'LBL_INTEGRATION_DATE',
    'type' => 'date',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'id' => 'Accountsintegration_date_c',
  );
?>