<?php
  $dictionary['Account']['fields']['last_activity_id_c'] = array(
    'inline_edit' => '',
    'labelValue' => 'Last Activity ID',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'last_activity_id_c',
    'vname' => 'LBL_LAST_ACTIVITY_ID',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id' => 'Accountslast_activity_id_c',
  );
?>