<?php
  // created: 2020-03-24 13:24:59
  $dictionary['Account']['fields']['supply_position_c'] = array (
    'inline_edit' => '1',
    'labelValue' => 'Supply Position',
    'required' => true,
    'source' => 'custom_fields',
    'name' => 'supply_position_c',
    'vname' => 'LBL_SUPPLY_POSITION',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'supply_position_list',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'Accountssupply_position_c',
  );
?>