<?php
	$dictionary['Case']['fields']['process_text_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Process Text',
		'required' => false,
		'source' => 'custom_fields',
		'name' => 'process_text_c',
		'vname' => 'LBL_PROCESS_TEXT',
		'type' => 'varchar',
		'massupdate' => '0',
		'default' => '',
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '255',
		'size' => '20',
		'id' => 'Casesprocess_text_c',
	);
?>