<?php
	$dictionary['Case']['fields']['quality_issue_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Quality Issue',
		'required' => false,
		'source' => 'custom_fields',
		'name' => 'quality_issue_c',
		'vname' => 'LBL_QUALITY_ISSUE',
		'type' => 'bool',
		'massupdate' => '0',
		'default' => '0',
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '255',
		'size' => '20',
		'id' => 'Casesquality_issue_c',
	);
?>