<?php
	$dictionary['Case']['fields']['user_id_c'] = array (
		'inline_edit' => 1,
		'required' => false,
		'source' => 'custom_fields',
		'name' => 'user_id_c',
		'vname' => 'LBL_SALES_REP_USER_ID',
		'type' => 'id',
		'massupdate' => '0',
		'default' => NULL,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => false,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '36',
		'size' => '20',
		'id' => 'Casesuser_id_c',
	);
?>