<?php
	$dictionary['Case']['fields']['immediate_action_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Immediate Action',
		'required' => false,
		'source' => 'custom_fields',
		'name' => 'immediate_action_c',
		'vname' => 'LBL_IMMEDIATE_ACTION',
		'type' => 'text',
		'massupdate' => '0',
		'default' => '',
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'size' => '20',
		'studio' => 'visible',
		'rows' => '4',
		'cols' => '20',
		'id' => 'Casesimmediate_action_c',
	);
?>