<?php
	$dictionary['Case']['fields']['create_date_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Create Date',
		'required' => true,
		'source' => 'custom_fields',
		'name' => 'create_date_c',
		'vname' => 'LBL_CREATE_DATE',
		'type' => 'date',
		'massupdate' => '0',
		'default' => '',
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => true,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'size' => '20',
		'enable_range_search' => false,
		'display_default' => 'now',
		'id' => 'Casescreate_date_c',
	);
?>