<?php
	$dictionary['Case']['fields']['qty_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Qty',
		'required' => false,
		'source' => 'custom_fields',
		'name' => 'qty_c',
		'vname' => 'LBL_QTY',
		'type' => 'decimal',
		'massupdate' => '0',
		'default' => '',
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '18',
		'size' => '20',
		'enable_range_search' => false,
		'precision' => '0',
		'id' => 'Casesqty_c',
	);
?>