<?php
	$dictionary['Case']['fields']['lot_number_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Lot Number',
		'required' => false,
		'source' => 'custom_fields',
		'name' => 'lot_number_c',
		'vname' => 'LBL_LOT_NUMBER',
		'type' => 'varchar',
		'massupdate' => '0',
		'default' => NULL,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '50',
		'size' => '20',
		'id' => 'Caseslot_number_c',
	);
?>