<?php
 // created: 2021-02-08 05:51:40
$dictionary['Case']['fields']['potential_return_c'] = array (
    'inline_edit' => '1',
    'labelValue' => 'Potential Return',
    'required' => true,
    'source' => 'custom_fields',
    'name' => 'potential_return_c',
    'vname' => 'LBL_POTENTIAL_RETURN',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'potential_return_list',
    'studio' => 'visible',
    'dependency' => NULL,
    'id' => 'Casespotential_return_c',
);
 ?>