<?php
	$dictionary['Case']['fields']['sales_rep_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Sales Rep',
		'required' => false,
		'source' => 'non-db',
		'name' => 'sales_rep_c',
		'vname' => 'LBL_SALES_REP',
		'type' => 'relate',
		'massupdate' => '0',
		'default' => NULL,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '255',
		'size' => '20',
		'id_name' => 'user_id_c',
		'ext2' => 'Users',
		'module' => 'Users',
		'rname' => 'name',
		'quicksearch' => 'enabled',
		'studio' => 'visible',
		'id' => 'Casessales_rep_c',
	);
?>