<?php
	$dictionary['Case']['fields']['customer_process_c'] = array (
		'inline_edit' => '1',
		'labelValue' => 'Customer Process',
		'required' => false,
		'source' => 'custom_fields',
		'name' => 'customer_process_c',
		'vname' => 'LBL_CUSTOMER_PROCESS',
		'type' => 'enum',
		'massupdate' => '0',
		'default' => NULL,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => 100,
		'size' => '20',
		'options' => 'customer_process_list',
		'studio' => 'visible',
		'dependency' => false,
		'id' => 'Casescustomer_process_c',
	);
?>