<?php
	// $dictionary['Case']['fields']['assigned_to_person_c'] = array (
	// 	'inline_edit' => '1',
	// 	'labelValue' => 'Assigned to Person',
	// 	'required' => true,
	// 	'source' => 'non-db',
	// 	'name' => 'assigned_to_person_c',
	// 	'vname' => 'LBL_ASSIGNED_TO_PERSON',
	// 	'type' => 'relate',
	// 	'massupdate' => '0',
	// 	'default' => NULL,
	// 	'no_default' => false,
	// 	'comments' => '',
	// 	'help' => '',
	// 	'importable' => 'true',
	// 	'duplicate_merge' => 'disabled',
	// 	'duplicate_merge_dom_value' => '0',
	// 	'audited' => false,
	// 	'reportable' => true,
	// 	'unified_search' => false,
	// 	'merge_filter' => 'disabled',
	// 	'len' => '255',
	// 	'size' => '20',
	// 	'id_name' => 'user_id1_c',
	// 	'ext2' => 'Users',
	// 	'module' => 'Users',
	// 	'rname' => 'name',
	// 	'quicksearch' => 'enabled',
	// 	'studio' => 'visible',
	// 	'id' => 'Casesassigned_to_person_c',
	// );
?>